### ISSUE TITLE
Tests for events

### ISSUE THREAD

**Issue by mateusz-glowinski** [pyeventsourcing/example-flask#5]
Hi,
I've seen in [documentation](https://eventsourcing.readthedocs.io/en/stable/topics/tutorial/part1.html#writing-tests) and [example-fastapi](https://github.com/pyeventsourcing/example-fastapi/) the test cases for `Application`.

Nevertheless, I've meet the expectations to have tests for `Events`.
Could you please add an example or give me a tip how such a test cases would look like based on this repository?

**Comment by johnbywater** [comment]
Hi @mglowinski93!

Thanks for your great question!

You can test the events of an application by reading the application's "notification log" has what you might expect.
https://eventsourcing.readthedocs.io/en/stable/topics/application.html#notification-log

It gives you event notification objects. You can convert event notification objects to domain event objects by calling the application's mapper method `to_domain_event()`.

You can test the domain events of an aggregate by collecting its pending events.
https://eventsourcing.readthedocs.io/en/stable/topics/domain.html#collecting-pending-events

Hope that helps?

**Comment by mateusz-glowinski** [comment]
Almost :)

I will try to be more accurate.

In your such a nice book (chapter 1), there is example of event:
```python
@dataclass(frozen=True)
class AccountOpened:
    originator_id: UUID
    originator_version: int
    timestamp: datetime
    full_name: str
```

and testcase for that:
```python
from uuid import uuid4


originator_id = uuid4()

event1 = AccountOpened(
    originator_id=originator_id,
    originator_version=1,
    timestamp=datetime.now(),
    full_name="Alice",
)

assert isinstance(event1.originator_id, UUID)
assert event1.originator_id == originator_id
assert event1.originator_version == 1
assert isinstance(event1.timestamp, datetime)
assert event1.full_name == "Alice"
```


Could you please tell me, how according to you, should be test case for below events?
According to me, it's really hard to test, since those `Events` do have relation to `Aggregate`.

```python
class TemplateCreated(AggregateCreated):
    template_info: TemplateInfo

    def apply(self, aggregate: Aggregate):
        aggregate.status = self.template_info.status
        aggregate.created_at = get_timestamp()
        aggregate.modified_at = None


class TemplateStarted(AggregateEvent):
    def apply(self, aggregate: "TemplateAggregate"):
        aggregate.status = TemplateStatus.IN_PROGRESS
        aggregate.modified_at = get_timestamp()
```

**Comment by johnbywater** [comment]
Oh yes, I see what you mean now.

I suppose there are two options:

1. If you want to test the "apply" methods as well, then you need a suitable aggregate fixture in each event test. Then you can test both that the event can be constructed, and also that it can be applied.

2. If you would prefer to define events without an "apply" method, and entirely without any reference to any aggregate, then you can do that. But then you need to write a separate mutator function, like the [Aggregate Example 6 in the docs](https://eventsourcing.readthedocs.io/en/stable/topics/examples/aggregate6.html#domain-model). Then you can test them, by simply testing that they can be constructed, because in this way they don't have anything else to test.

Does this answer your question? I suppose the docs have aggregate tests because I was trying to show that event sourced aggregates can be used and tested just like non-event sourced aggregates, in that they have command and query methods. But it's also important to check the events.

**Comment by mateusz-glowinski** [comment]
Yes, it does. That you very much!
